02-VueCalculator solved
js-tasks-ru/vue-20230120_nikita804 pull request #3
Opened 2023-01-29 13:31 UTC by nbmprod

Добрый день! Решил с watch, почему-то было не понятно, как использовать computed в этой задаче...

2023-01-30 10:09 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-01-30 10:15 UTC, nbmprod commented
Добрый день! Решение 3-й задачи автоматически поместилось в пулл реквест второй задачи...
03-MarkedList тоже не получилось решить с computed. Я понимаю, как получить доступ к элементам массива со строками, которые будут будут совпадать с inputValue, но не понимаю, как на этой основе получить доступ к соответствующим html элементам, чтобы навесить на них marked

2023-01-31 14:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-01-31 23:52 UTC, ShGKme requested changes
Требуется разобраться с вычисляемыми свойствами. Решение в калькуляторе очень легко переделывается на решение с вычисляемым свойством. Достаточно перенести метод в `computed` и использовать свойство в рендеринге.

2023-01-31 23:52 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +    },
Через этот метод и два отслеживания фактически реализовано вычисляемое свойство в свойстве `result`. 

Свойство `result` не имеет никакого собственного значения, кроме как результата вычисления методом `calculate`, и обновляется через отслеживание всегда, когда меняются `inputs` и `operation` - все зависимости этого вычисления. Лучше явно описать `result` - как вычисляемое свойство. Тогда сразу из описания компонента будет видно, что свойство именно вычисляемое, а зависимости определятся самим Vue автоматически.

Описание вычисляемого свойства даже не будет отличаться от метода `calculate`.

2023-01-31 23:52 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +          >{{email}}</li>
Здесь через `includes` реализована логика маркировки строк в шаблоне. Лучше держать шаблон максимально простым, не перенося в него логики обработки данных. Код в шаблоне сложно отлаживать, а выполняться он будет при каждом рендеринге. Для переноса логики из шаблон и чтобы ещё раз попрактиковаться в работе с вычисляемыми свойствами лучше перенести эту логику в подготовку данных к отображению в вычисляемом свойстве. В нём требуется вычислить такие данные, которые позволят при выводе строк сразу знать, промаркирована она или нет, без сложных вычислений.

2023-02-02 13:07 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-02 13:08 UTC, nbmprod commented
Григорий, добрый день! 
Решил 02 с computed, теперь все понятно!
Решил 03 с methods. Вроде бы принцип невмешательства в template соблюдается. Правда в описании задания указывается, что можно решить с computed, но я не понимаю как

2023-02-03 20:11 UTC, ShGKme requested changes
Для практики работы с вычисляемым свойствами лучше добить решение `01-basics/03-MarkedList` через вычисляемое свойство. Оставил в комментарии подсказку. Пишите, если нужна более прямая подсказка.

2023-02-03 20:11 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +    },
Эта логика перенеслась из шаблона в методы, что облегчает визуально шаблон.
Но всё ещё логика работы с данными реализуется в шаблоне. В целом для такого простого вычисления это допустимо. Но лучше делать это вычисляемым свойством.

Нужно как-то так подготовить данные, чтобы при выводе можно было сразу знать, промаркирована почта или нет. Например, это можно сделать, вычисляя из массива строк-почт массив объектов, где есть и почта, и флаг маркировки.

2023-02-04 11:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-04 15:30 UTC, ShGKme reviewed
Все решённые задачи приняты, но есть новые добавленные задачи.

2023-02-05 06:26 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-05 06:29 UTC, nbmprod commented
Григорий, добрый день! Отправляю решенные задачи. Запутался с гитхабом из-за того, что сделал пулл задачи из второй темы прямо в мастер... в дальнейшем буду делать пулл в соответствующую локальную ветку и не мержить ее с мастером, пока предыдущие задачи не приняты

2023-02-05 15:07 UTC, ShGKme approved these changes
Все задачи приняты

2023-02-05 15:07 UTC, merged